formatter: markdown

content: |-
  {{ .Header }}

  ## Example

  ```hcl
  {{ include "example/main.tf" }}
  ```

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Modules }}

  {{ .Requirements }}

  {{ .Providers }}
